name: Use Github App
on:
  workflow_dispatch:

jobs:
  checkout-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: get token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.GH_APPLICATION_ID }}
          private-key: ${{ secrets.GH_APPLICATION_KEY }}
          owner: ${{ github.repository_owner }}

      - name: create label on current repo
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          OWNER: rameshk553
          REPO: poc-github-app
          LABEL_NAME: my-label
          LABEL_COLOR: F29513
        run:  |
          REPO_ID=$(gh api graphql -f query="query { repository(owner: \"$OWNER\", name: \"$REPO\") { id } }" \
            --jq '.data.repository.id')

          gh api graphql -f query="mutation {
            createLabel(input: {
              repositoryId: \"$REPO_ID\",
              name: \"$LABEL_NAME\",
              color: \"$LABEL_COLOR\"
            }) {
              label {
                name
              }
            }
          }"

      - name: create label on another repo
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          OWNER: rameshk553
          REPO: test-poc-github-app
          LABEL_NAME: my-label1
          LABEL_COLOR: F29513
        run:  |
          REPO_ID=$(gh api graphql -f query="query { repository(owner: \"$OWNER\", name: \"$REPO\") { id } }" \
            --jq '.data.repository.id')

          gh api graphql -f query="mutation {
            createLabel(input: {
              repositoryId: \"$REPO_ID\",
              name: \"$LABEL_NAME\",
              color: \"$LABEL_COLOR\"
            }) {
              label {
                name
              }
            }
          }"
      
